### ISSUE TITLE
Compatibily with boostrap 4.6?

### ISSUE THREAD

**Issue by JuanCamilo0809** [talis/ng-context-menu#7]
I have error with boostrap 4.6, don´t show nothing.

Do you have any solution?
Thanks,

**Comment by ghost** [comment]
In my case at least, one solution seems to be to add this CSS rule:

```css
.open > .dropdown-menu {
  display: block;
}
```
